# Generated by Django 4.2.19 on 2025-02-18 15:02

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNodeModel',
            fields=[
                ('host', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('allowIn', models.BooleanField(default=False)),
                ('inUsername', models.CharField(max_length=512)),
                ('inPassword', models.CharField(default=core.tools.generate_password, max_length=512)),
                ('allowOut', models.BooleanField(default=False)),
                ('outUsername', models.CharField(max_length=512)),
                ('outPassword', models.CharField(max_length=512)),
            ],
        ),
    ]
