# Generated by Django 4.2.19 on 2025-02-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0008_remove_followrequestmodel_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequestModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='follow', max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='authors.authormodel', to_field='id')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='authors.authormodel', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='FollowerModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='authors.authormodel', to_field='id')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='authors.authormodel', to_field='id')),
            ],
        ),
    ]
