"""
Django settings for socialapp project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
import os, dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(".env", override=True)
LOCAL_HOST = os.getenv("LOCAL_HOST", "http://127.0.0.1:8000/")
API_HOST = LOCAL_HOST + "api/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "default-secret-key")
CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]  # Update as needed
CSRF_COOKIE_HTTPONLY = False  # Allows JS to read the CSRF token

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=True))

ALLOWED_HOSTS = ['*']
DJANGO_API_URL = os.getenv("http://localhost:8000", "http://127.0.0.1:8000")

# Enable secure cookies
SESSION_COOKIE_SECURE = True  # Ensures cookie is only sent over HTTPS

# Ensure the cookie is HttpOnly
SESSION_COOKIE_HTTPONLY = True  # Makes the session cookie inaccessible to JavaScript

# Restrict cross-site cookies
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevents cookies from being sent with cross-site requests

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Application definition
INSTALLED_APPS = [
    'corsheaders', # I need it to handle cross origin requests
    'rest_framework',
    'authors',
    'follow',  
    'posts',
    'comments_likes',
    'markdownify',
    'inbox',
    'core',
    'socialapp',
        
    'sslserver', #for https locally
    'csp',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    'whitenoise.runserver_nostatic', #added for static serving
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.LavenderAuth', 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise middleware for static files
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # X-Frame options middleware
    'csp.middleware.CSPMiddleware',
]


ROOT_URLCONF = 'socialapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Location for our HTML Templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialapp.wsgi.application'


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "lavender_db",
        "USER": "test1",
        "PASSWORD": "12345",
        "HOST": "localhost",
        "PORT": "5432",  }
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

IMAGE_URL = '/images/'
IMAGE_ROOT = MEDIA_ROOT / 'images'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Content Security Policy
CSP_DEFAULT_SRC = (
    "'self'",

)
CSP_SCRIPT_SRC = (
    "'self'", "blob:", "https://cdn.jsdelivr.net",

)
CSP_STYLE_SRC = (
    "'self'", "'unsafe-inline'", '*',

)
CSP_IMG_SRC = (
    "'self'", "data:", '*',
)
CSP_CONNECT_SRC = (
    "'self'", '*',

)
CSP_FONT_SRC = (
    "'self'", '*',
)
CSP_FRAME_SRC = (
    "'self'", '*',
    "https://www.youtube.com/"
)
CSP_FRAME_ANCESTORS = ("'none'")

SPECTACULAR_SETTINGS = {
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'DISABLE_ERRORS_AND_WARNINGS': True,
    'TITLE': 'Lavender API',
    'VERSION': '1.0.0',
}