# Generated by Django 4.2.20 on 2025-03-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('application/base64', 'Image'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], max_length=64)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authormodel', to_field='id')),
            ],
        ),
    ]
