# Generated by Django 4.2.19 on 2025-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.URLField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.URLField(blank=True),
        ),
    ]
