# Generated by Django 4.2.19 on 2025-02-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_remove_likemodel_author_remove_likemodel_comment_and_more'),
        ('posts', '0005_alter_comment_author_alter_like_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], max_length=64)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='authors.authormodel', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='like', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('object', models.CharField(max_length=1024)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to='authors.authormodel', to_field='id')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='posts.commentmodel', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('application/base64', 'Image'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], max_length=64)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authormodel', to_field='id')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='posts.postmodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.postmodel', to_field='id'),
        ),
    ]
