# Generated by Django 4.2.19 on 2025-02-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_commentmodel_likemodel_postmodel_remove_like_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
