# Generated by Django 4.2.19 on 2025-02-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0007_remove_likemodel_author_remove_likemodel_comment_and_more'),
        ('authors', '0009_remove_likemodel_author_remove_likemodel_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], max_length=64)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='authors.authormodel', to_field='id')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.postmodel', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='like', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('object', models.CharField(max_length=1024)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to='authors.authormodel', to_field='id')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='comments_likes.commentmodel', to_field='id')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='posts.postmodel', to_field='id')),
            ],
        ),
    ]
