# Generated by Django 4.2.20 on 2025-03-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('lastGithubUpdate', models.DateTimeField(auto_now_add=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('type', models.CharField(default='author', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('host', models.CharField(blank=True, max_length=1024)),
                ('displayName', models.CharField(blank=True, max_length=512)),
                ('github', models.CharField(blank=True, max_length=1024)),
                ('profileImage', models.CharField(blank=True, max_length=1024)),
                ('page', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
