# Generated by Django 4.2.19 on 2025-02-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
