# Generated by Django 4.2.19 on 2025-02-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('username', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('lastGithubUpdate', models.DateTimeField(auto_now_add=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('type', models.CharField(default='author', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('host', models.CharField(blank=True, max_length=1024)),
                ('displayName', models.CharField(blank=True, max_length=512)),
                ('github', models.CharField(blank=True, max_length=1024)),
                ('profileImage', models.CharField(blank=True, max_length=1024)),
                ('page', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown')], max_length=64)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequestModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='follow', max_length=64)),
                ('summary', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='like', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('object', models.CharField(max_length=1024)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=64)),
                ('id', models.CharField(max_length=1024, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('application/base64', 'Image'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], max_length=64)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], max_length=64)),
            ],
        ),
    ]
