# Generated by Django 4.2.19 on 2025-02-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_author_alter_like_author_and_more'),
        ('authors', '0006_authormodel_commentmodel_followermodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='authors.commentmodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='authors.postmodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='followrequestmodel',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='followrequestmodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='followermodel',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='followermodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='authors.authormodel', to_field='id'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='authors.postmodel', to_field='id'),
        ),
    ]
