# Generated by Django 4.2.19 on 2025-02-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_delete_author_postmodel_author_likemodel_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequestmodel',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='followrequestmodel',
            name='object',
        ),
        migrations.DeleteModel(
            name='FollowerModel',
        ),
        migrations.DeleteModel(
            name='FollowRequestModel',
        ),
    ]
