# Generated by Django 4.2.19 on 2025-02-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_remove_followrequestmodel_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
